---
- name: Check if the config file exists
  ansible.builtin.stat:
    path: "{{ var_ipv6_sysctl_settings_file }}"
  register: reg_ipv6_sysctl_file

- name: Create the configuration file
  ansible.builtin.file:
    path: "{{ var_ipv6_sysctl_settings_file }}"
    state: touch
    owner: root
    group: root
    mode: '0644'
  become: true
  when: not reg_ipv6_sysctl_file['stat']['exists']

- name: Apply IPv6 sysctl settings
  block:

    - name: Configure Accepting Router Advertisements on All IPv6 Interfaces
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.accept_ra
        value: "{{ var_net_ipv6_conf_all_accept_ra }}"
        state: "{{ var_ipv6_sysctl_state }}"
        sysctl_file: "{{ var_ipv6_sysctl_settings_file }}"
      become: true
      when: var_net_ipv6_conf_all_accept_ra in [0, 1]

    - name: Disable Accepting ICMP Redirects for All IPv6 Interfaces
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.accept_redirects
        value: "{{ var_net_ipv6_conf_all_accept_redirects }}"
        state: "{{ var_ipv6_sysctl_state }}"
        sysctl_file: "{{ var_ipv6_sysctl_settings_file }}"
      become: true
      when: var_net_ipv6_conf_all_accept_redirects in [0, 1]

    - name: Disable Kernel Parameter for Accepting Source-Routed Packets on all IPv6 Interfaces
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.accept_source_route
        value: "{{ var_net_ipv6_conf_all_accept_source_route }}"
        state: "{{ var_ipv6_sysctl_state }}"
        sysctl_file: "{{ var_ipv6_sysctl_settings_file }}"
      become: true
      when: var_net_ipv6_conf_all_accept_source_route in [0, 1]

    - name: Disable Kernel Parameter for IPv6 Forwarding
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: "{{ var_net_ipv6_conf_all_forwarding }}"
        state: "{{ var_ipv6_sysctl_state }}"
        sysctl_file: "{{ var_ipv6_sysctl_settings_file }}"
      become: true
      when: var_net_ipv6_conf_all_forwarding in [0, 1]

    - name: Disable Accepting Router Advertisements on all IPv6 Interfaces by Default
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.accept_ra
        value: "{{ var_net_ipv6_conf_default_accept_ra }}"
        state: "{{ var_ipv6_sysctl_state }}"
        sysctl_file: "{{ var_ipv6_sysctl_settings_file }}"
      become: true
      when: var_net_ipv6_conf_default_accept_ra in [0, 1]

    - name: Disable Kernel Parameter for Accepting ICMP Redirects by Default on IPv6 Interfaces
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.accept_redirects
        value: "{{ var_net_ipv6_conf_default_accept_redirects }}"
        state: "{{ var_ipv6_sysctl_state }}"
        sysctl_file: "{{ var_ipv6_sysctl_settings_file }}"
      become: true
      when: var_net_ipv6_conf_default_accept_redirects in [0, 1]

    - name: Disable Kernel Parameter for Accepting Source-Routed Packets on IPv6 Interfaces by Default
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.accept_source_route
        value: "{{ var_net_ipv6_conf_default_accept_source_route }}"
        state: "{{ var_ipv6_sysctl_state }}"
        sysctl_file: "{{ var_ipv6_sysctl_settings_file }}"
      become: true
      when: var_net_ipv6_conf_default_accept_source_route in [0, 1]

  when: var_ipv6_sysctl_state in ["present", "absent"]
