---
###########################################################################################
# Certain kernel parameters should be set for systems which are acting as either hosts or
# routers to improve the system's ability defend against certain types of IPv4 protocol
# attacks.
###########################################################################################

#
# [Disable Accepting ICMP Redirects for All IPv4 Interfaces]
#
# ICMP redirect messages are used by routers to inform hosts that a more direct route exists for a particular
# destination. These messages modify the host's route table and are unauthenticated. An illicit ICMP redirect message
# could result in a man-in-the-middle attack.
# This feature of the IPv4 protocol has few legitimate uses. It should be disabled unless absolutely required."
#
var_net_ipv4_conf_all_accept_redirects: 0

#
# [Disable Kernel Parameter for Accepting ICMP Redirects by Default on IPv4 Interfaces]
#
# ICMP redirect messages are used by routers to inform hosts that a more direct route exists for a particular
# destination. These messages modify the host's route table and are unauthenticated. An illicit ICMP redirect message
# could result in a man-in-the-middle attack.
# This feature of the IPv4 protocol has few legitimate uses. It should be disabled unless absolutely required.
#
var_net_ipv4_conf_default_accept_redirects: 0

#
# [Disable Kernel Parameter for Accepting Source-Routed Packets on all IPv4 Interfaces]
#
# Source-routed packets allow the source of the packet to suggest routers forward the packet along a different path than
# configured on the router, which can be used to bypass network security measures. This requirement applies only to the
# forwarding of source-routerd traffic, such as when IPv4 forwarding is enabled and the system is functioning as a
# router.
#
# Accepting source-routed packets in the IPv4 protocol has few legitimate uses. It should be disabled unless it is
# absolutely required.
#
var_net_ipv4_conf_all_accept_source_route: 0

#
# [Disable Kernel Parameter for Accepting Source-Routed Packets on IPv4 Interfaces by Default]
#
# Source-routed packets allow the source of the packet to suggest routers forward the packet along a different path than
# configured on the router, which can be used to bypass network security measures.
# Accepting source-routed packets in the IPv4 protocol has few legitimate uses. It should be disabled unless it is
# absolutely required, such as when IPv4 forwarding is enabled and the system is legitimately functioning as a router.
#
var_net_ipv4_conf_default_accept_source_route: 0

#
# [Enable Kernel Parameter to Log Martian Packets on all IPv4 Interfaces]
#
# The presence of "martian" packets (which have impossible addresses) as well as spoofed packets, source-routed packets,
# and redirects could be a sign of nefarious network activity. Logging these packets enables this activity to be
# detected.
#
var_net_ipv4_conf_all_log_martians: 1

#
# [Enable Kernel Paremeter to Log Martian Packets on all IPv4 Interfaces by Default]
#
# The presence of "martian" packets (which have impossible addresses) as well as spoofed packets, source-routed packets,
# and redirects could be a sign of nefarious network activity. Logging these packets enables this activity to be
# detected.
#
var_net_ipv4_conf_default_log_martians: 1

#
# [Enable Kernel Parameter to Use Reverse Path Filtering on all IPv4 Interfaces]
#
# Enabling reverse path filtering drops packets with source addresses that should not have been able to be received on
# the interface they were received on. It should not be used on systems which are routers for complicated networks, but
# is helpful for end hosts and routers serving small networks.
#
var_net_ipv4_conf_all.rp_filter: 1

#
# [Enable Kernel Parameter to Use Reverse Path Filtering on all IPv4 Interfaces by Default]
#
# Enabling reverse path filtering drops packets with source addresses that should not have been able to be received on
# the interface they were received on. It should not be used on systems which are routers for complicated networks, but
# is helpful for end hosts and routers serving small networks.
#
var_net_ipv4_conf_default_rp_filter: 1

#
# [Disable Kernel Parameter for Accepting Secure ICMP Redirects on all IPv4 Interfaces]
#
# Accepting "secure" ICMP redirects (from those gateways listed as default gateways) has few legitimate uses. It should
# be disabled unless it is absolutely required.
#
var_net_ipv4_conf_all_secure_redirects: 0

#
# [Configure Kernel Parameter for Accepting Secure Redirects By Default]
#
# Accepting "secure" ICMP redirects (from those gateways listed as default gateways) has few legitimate uses. It should
# be disabled unless it is absolutely required.
#
var_net_ipv4_conf_default_secure_redirects: 0

#
# [Enable Kernel Parameter to Ignore ICMP Broadcast Echo Requests on IPv4 Interfaces]
#
# Responding to broadcast (ICMP) echoes facilitates network mapping and provides a vector for amplification attacks.
# Ignoring ICMP echo requests (pings) sent to broadcast or multicast addresses makes the system slightly more difficult
# to enumerate on the network.
#
var_net_ipv4_icmp_echo_ignore_broadcasts: 1

#
# [Enable Kernel Parameter to Ignore Bogus ICMP Error Responses on IPv4 Interfaces]
#
# Ignoring bogus ICMP error responses reduces log size, although some activity would not be logged.
#
var_net_ipv4_icmp_ignore_bogus_error_responses: 1

#
# [Enable Kernel Parameter to Use TCP Syncookies on IPv4 Interfaces]
#
# A TCP SYN flood attack can cause a denial of service by filling a system's TCP connection table with connections in
# the SYN_RCVD state. Syncookies can be used to track a connection when a subsequent ACK is received, verifying the
# initiator is attempting a valid connection and is not a flood source. This feature is activated when a flood condition
# is detected, and enables the system to continue servicing valid connection requests.
#
var_net_ipv4_tcp_syncookies: 1

#
# [Disable Kernel Parameter for Sending ICMP Redirects on all IPv4 Interfaces]
#
# ICMP redirect messages are used by routers to inform hosts that a more direct route exists for a particular
# destination. These messages contain information from the system's route table possibly revealing portions of the
# network topology.
# The ability to send ICMP redirects is only appropriate for systems acting as routers.
#
var_net_ipv4_conf_all_send_redirects: 0

#
# [Disable Kernel Parameter for Sending ICMP Redirects on all IPv4 Interfaces by Default]
#
# ICMP redirect messages are used by routers to inform hosts that a more direct route exists for a particular
# destination. These messages contain information from the system's route table possibly revealing portions of the
# network topology.
# The ability to send ICMP redirects is only appropriate for systems acting as routers.
#
var_net_ipv4_conf_default_send_redirects: 0

#
# [Disable Kernel Parameter for IP Forwarding on IPv4 Interfaces]
#
# Routing protocol daemons are typically used on routers to exchange network topology information with other routers. If
# this capability is used when not required, system network information may be unnecessarily transmitted across the
# network.
#
var_net_ipv4_ip_forward: 0
